myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
 path(r'login/', views.user_login, name='login'),
 path(r'logout/', views.user_logout, name='logout'),
 path(r'', views.index, name='index'),
 path(r'about/', views.about, name='about'),
 path(r'<int:cat_no>/', views.detail, name='detail'),
 path(r'products/', views.products, name='products'),
 path(r'placeorder/', views.place_order, name='placeorder'),
 path(r'products/<int:prod_id>/', views.productdetail, name='productdetail'),
 path(r'orders/', views.myorders, name='orders'),
 path(r'register/', views.user_register, name='register'),
 # path(r'orders/', views.myorders, name='orders'),
 path(r'forgot_password/', views.forgot_password, name='forgot_password')

]

mysiteF22/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),

]

myapp/models.py
from django.db import models
import datetime
from datetime import date
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

# def validate_stock(value):
#     if value >= 1000:
#         raise ValidationError(
#             _('%(value)s is greater then 1000'),
#             params={'value': value},
#         )
#     elif value <=0:
#         raise ValidationError(
#             _('%(value)s is less then 0'),
#             params={'value': value},
#         )

class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=20, default='Windsor')

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100, validators=[MinValueValidator(0),MaxValueValidator(1000)])
    available = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def refill(self):
        self.stock = self.stock + 100
        return self.stock


class Client(User):
    PROVINCE_CHOICES = [
    ('AB', 'Alberta'),
    ('MB', 'Manitoba'),
    ('ON', 'Ontario'),
    ('QC', 'Quebec'),]
    company = models.CharField(max_length=50, blank=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default="Windsor")
    province=models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)
    clientImage = models.ImageField(upload_to='clientImages/', blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Order(models.Model):
    product = models.ForeignKey(Product, related_name="orders",on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='orders', on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField()
    ORDER_STAGES = [(0, 'Order Cancelled'), (1, 'Order Placed'), (2, 'Order Shipped'), (3, 'Order Delivered'), ]
    order_status = models.IntegerField(choices=ORDER_STAGES, default=1)
    status_date = models.DateField(default=date.today())

    def __str__(self):
        # return self.product._str() + '--' + self.client.str_()
        orderstatus = self.order_status
        return 'Date: ' + self.status_date.strftime("%x") + ', Status: ' + self.ORDER_STAGES[orderstatus][
            1] + ', Client: ' + self.client.first_name + ' ' + self.client.last_name + ' ,Product: ' + self.product.name


    def total_cost(self):
        return self.product.price * self.num_units

myapp/forms.py
from django import forms
from myapp.models import Order, Client, Product
from django.contrib.auth.forms import UserCreationForm


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order   #models we want to represent
        fields = ['client', 'product', 'num_units']      #fields we want to output

    client = forms.ModelChoiceField(widget=forms.RadioSelect, queryset=Client.objects.all(), to_field_name="username", label='Client name')
    product = forms.ModelChoiceField(queryset=Product.objects.all().order_by('id'), to_field_name="name")
    num_units = forms.IntegerField(label='Quantity')


class InterestForm(forms.Form):
    INT_CHOICES = [('Yes', 'Yes'), ('No', 'No')]
    interested = forms.ChoiceField(widget=forms.RadioSelect, choices=INT_CHOICES)
    quantity = forms.IntegerField(initial=1)
    comments = forms.CharField(widget=forms.Textarea, label='Additional Comments', required=False)

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True,)
    last_name = forms.CharField(max_length=100, required=True)
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())
    # confirm_password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())
    email = forms.EmailField(required=True)

    class Meta:
        model = Client
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class ForgotPasswordForm(forms.Form):
    Email = forms.EmailField()

    def __str__(self):
        return self.Email

myapp/views.py
from django.conf.global_settings import EMAIL_HOST_USER
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import render
from .forms import InterestForm, OrderForm, ForgotPasswordForm, RegisterForm
from datetime import date
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
import hashlib
import random
import string
from django.contrib import messages

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .models import Category, Product, Client, Order
from datetime import datetime

# Create your views here.


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                if 'last_login' in request.session:
                    messages.success(request, 'Last login date and time: ' + str(request.session['last_login']))
                else:
                    request.session['last_login'] = str(timezone.now())
                    # print(request.session['last_login'])
                    messages.success(request, "Your last login was more than 1 hour ago")

                request.session['last_login'] = str(timezone.now())

                request.session['username'] = username
                request.session['user_first_name'] = user.first_name
                request.session['user_last_name'] = user.last_name
                request.session.set_expiry(3600)

                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:login'))

def index(request):
    cat_list = Category.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'cat_list': cat_list})
    product_list = Product.objects.all().order_by('-price')[:5]
    response = HttpResponse()
    heading1 = '<p>' + 'List of categories: ' + '</p>'
    response.write(heading1)
    for category in cat_list:
        para = '<p>'+ str(category.id) + ': ' + str(category) + '</p>'
        response.write(para)
    heading2 = '<p>' + 'List of products: ' + '</p>'
    response.write(heading2)
    for product in product_list:
        para = '<p>' + str(product.id)+':' + str(product) + '</p>'
        response.write(para)
    return response


def about(request):
    # return render(request, 'myapp/about.html')
    # return HttpResponse("This is an online store App")

    if 'about_visits' in request.COOKIES:
        count_visited = int(request.COOKIES['about_visits'])
        response = render(request, 'myapp/about.html', {'no_of_times_visited': count_visited + 1})
        response.set_cookie('about_visits', count_visited + 1, max_age=300)
    else:
        response = render(request, 'myapp/about.html', {'no_of_times_visited': 1})
        response.set_cookie('about_visits', 1)
    return response


def detail(request, cat_no):
    category = get_object_or_404(Category, pk=cat_no)
    products = Product.objects.filter(category=category)
    return render(request, 'myapp/detail.html', {'category': category, 'products': products})
    # detail_response = HttpResponse()
    # heading = '<p>' + 'Warehouse location :' + category.warehouse + '</p>'
    # heading += '<p>' + 'List of products' + '</p>'
    # detail_response.write(heading)
    #
    # for product in products:
    #     para = '<p>' + str(product.id) + ':' + str(product) + '</p>'
    #     detail_response.write(para)
    # return detail_response

def products(request):
    prodlist = Product.objects.all().order_by('id')[:10]
    return render(request, 'myapp/products.html', {'prodlist': prodlist})

def place_order(request):
    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST, initial={'status_date': date.today(), 'order_status': 'Order Placed'})
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units <= order.product.stock:
                prod = Product.objects.filter(id=order.product.id).first()
                prod.stock -= order.num_units
                prod.save()
                order.save()
                msg = 'Your order has been placed successfully'
            else:
                msg = 'We do not have sufficient stock to fill your order.'
            return render(request, 'myapp/order_response.html', {'msg': msg})

    else:
        form = OrderForm()
        return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prodlist': prodlist})

def productdetail(request, prod_id):
    prod = Product.objects.get(pk=prod_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['interested'] == 'Yes':
                prod.interested = prod.interested + 1
                print(prod.id)
                prod.save()
                return redirect('/myapp/')
            else :
                return redirect('/myapp/')
    else:
        form = InterestForm()
        return render(request, 'myapp/productdetail.html', {'form': form, 'prod': prod})

@login_required
def myorders(request):
    try:
        user = request.user
        print(user)
        client = Client.objects.get(username=user.username)
        orders = Order.objects.filter(client=client)
        msg = f'Orders placed by {client} :-'
        if orders.count() == 0:
            msg = 'Client has not placed any orders'
        return render(request, 'myapp/myorders.html', {'orders': orders, 'msg': msg})
    except Client.DoesNotExist:
        msg = 'You are not a registered client'
        return render(request, 'myapp/myorders.html', {'msg': msg})

def user_register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect("myapp:login")
        else:
            print('form invalid')
    else:
        form = RegisterForm()
    return render(request=request, template_name="myapp/register.html", context={"register_form": form})

def forgot_password(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            random_password = ''.join(random.choice(string.ascii_letters) for i in range(10))
            password = make_password(random_password)
            Client.objects.filter(email=form.cleaned_data['Email']).update(password=password)

            subject = 'New Password'
            message = 'Your new password is ' + random_password
            recipient = form.cleaned_data['Email']
            send_mail(subject, message, EMAIL_HOST_USER, [recipient], fail_silently=False)
            return HttpResponse('A password has been sent to your inbox')
        else:
            return HttpResponse('Incorrect details')
    else:
        form = ForgotPasswordForm()
        return render(request, 'myapp/forgot_password.html', {'form': form})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}About{% endblock %}
{% block myhdg %} Hello Top GUN {% endblock %}
{% block body_block %}
    <h3>This is an Online Store App</h3>
    {% if no_of_times_visited %}
        <p>Number of times this page visited - {{ no_of_times_visited }}</p>
    {% endif %}
    {#    <p><a href="{% url 'myapp:index' %}">Index page using URL namespacing</a></p>#}
    {#    <p><a href="/myapp/">Index page using hardcoded URL</a></p>#}
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h3>This is an Online Store App</h3>
    <p><a href="{% url 'myapp:index' %}">Index page using URL namespacing</a></p>
    <p><a href="/myapp/">Index page using hardcoded URL</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
</head>

<body class="bodybackground">
    <div class="container-fluid">
        <h1>
            {% block myhdg %}
        {% if user.is_authenticated %}
            Hello {{ user.username }}
        {% else %}
            Hello User
        {% endif %}

    {% endblock %}</h1>
    {% block body_block %}*** {% endblock %}
    </div>
    <hr />
    <div>
        <ul >
        {% block line_block %}
            <li class="hbar1">
                <a href="/myapp/about">Find out about this site</a>
            </li>

            <li class="hbar1"><a href="{% url 'myapp:products' %}">Click here to
            see products</a></li>
            {% if user.is_authenticated %}
                <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a></li>
                <li class="hbar1"><a href="{% url 'myapp:orders' %}">Products Ordered</a></li>
            {% else %}
                <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
                <li class="hbar1"><a href="{% url 'myapp:register' %}">Register</a></li>
            {% endif %}
            <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to
                return to main page</a><br/></li>
        {% endblock %}

        </ul>
    </div>
<footer >Copyright Top Gun</footer>
</body>

</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}Detail{% endblock %}
{% block myhdg %} Hello Top GUN {% endblock %}
{% block body_block %}
    {% if category %}
        <h3>Category Name - {{ category.name }}</h3>
        <h4>Category Warehouse - {{ category.warehouse }}</h4>
        <h4>List of products for the {{ category.name }} category</h4>
        <ol >
            {% for product in products %}
                <li> {{ product.name }} </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
{#    <p><a href="{% url 'myapp:index' %}">Index page</a></p>#}
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail page</title>
</head>
<body>
{% if category %}
    <h3>Category Name - {{ category.name }}</h3>
    <h4>Category Warehouse - {{ category.warehouse }}</h4>
    <h4>List of products for the {{ category.name }} category</h4>
    <ol>
        {% for product in products %}
            <li> {{ product.name }} </li>
        {% endfor %}
    </ol>
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
<p><a href="{% url 'myapp:index' %}">Index page</a></p>
</body>
</html>

myapp/templates/myapp/forgot_password.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<h1>Site Forgot Password</h1>
<form action="{% url 'myapp:forgot_password' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<input class = "btn btn-success" type="submit" name="submit1" value="Send email" />
</form>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block myhdg %} Hello {{ user }} {% endblock %}
{% block body_block %}
    <p>Last Login - {{ last_login }}</p>

    {% if cat_list %}
        <h3>List of Categories</h3>
        <ol>
            {% for cat in cat_list %}
                <li><a href="{{ cat.id }}/">{{ cat.name }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
    {#    <p><a href="{% url 'myapp:about' %}">About page</a></p>#}
{% endblock %}
{% block link_block %}
    <li class="hbar1"><a href="/myapp/about/">Find out about this
        site</a></li>
    <li class="hbar1"><a href="{% url 'myapp:products' %}">Click here to
        see products</a></li>
    {% if user.is_authenticated %}
        <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a></li>
    {% else %}
        <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
    {% endif %}<br/></li>
{% endblock link_block %}

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
 <meta charset="UTF-8">
 <title>Online Store APP</title>
</head>
<body>
 {% if cat_list %}
 <h2>List of Categories</h2>
 <ol>
 {% for cat in cat_list %}
 <li> {{ cat.name}} </li>
 {% endfor %}
 </ol>
 {% else %}
 <strong>There are no available categories!</strong>
 {% endif%}
<p><a href="{% url 'myapp:about' %}">About page</a></p>
</body>
</html>

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h2>Orders</h2>
    {% if orders %}
        {% for order in orders %}
            <li> {{ order.product }} : {{ order.num_units }} </li>
        {% endfor %}
    {% else %}
        {{ msg }}
    {% endif %}
{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if msg %}
    <h3>{{ msg }}</h3>
    {% endif %}
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if prodlist %}
        <h4> Products : </h4>
        <ul>
            {% for prods in prod_list %}
            <li>
                {{prods.name}}
            </li>
            {% endfor %}
        </ul>
    {% endif %}
<div class="form-group">
    <form action="/myapp/placeorder/" method="post" >
        {% csrf_token %}
        {{form}}
        <input type="submit" value="submit" class = "btn btn-success">
        {% if msg %}
            <p>{{msg}}</p>
        {% endif %}
    </form>
    </div>
{% endblock %}

myapp/templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
        {% if prod.available %}
            <h3>{{ prod.name }}</h3>
            <h4>People interested : {{ prod.interested }}</h4>
            <h4>Price : {{ prod.price }}</h4>
        {% else %}
            <h3>Product {{ prod.name }} is not available</h3>
        {% endif %}
    <form action="{% url 'myapp:productdetail' prod.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="sumbit" class="btn btn-primary">
    </form>
{% endblock %}

myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if prodlist %}
        <h4> Products : </h4>
        <ul>
            {% for prods in prodlist %}
            <li>
                <p><a href={% url 'myapp:productdetail' prods.id %}>{{ prods.name}}</p>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    <p><a href="{% url 'myapp:placeorder' %}">Place order</a></p>
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block title %}Register Page{% endblock %}
{% block body_block %}
    <div class="form-group">
        <h3 style="text-align: left;">Register</h3>
        <form method="POST">
            {% csrf_token %}
            {{ register_form}}{{ linebreaks }}

            <button class="btn btn-primary" type="submit">Register</button>
        </form>
    </div>
{% endblock %}
{% block link_block %}
    <li class="hbar1"><a href="{% url 'myapp:login' %}">Login if already registered</a></li>
    <br/>
{% endblock link_block %}